server:
  port: 18086


spring:
  profiles:
    active: dev
  application:
    name: "luxan-ai-park"


lewin:
  luxan-ai-park:
    scene-list:
      - name: "南部厂餐厅"
        camera-info-list:
          - name: "神目"
            ip: 192.168.32.43
            location: "东门：进"
            type: deepcam
          - name: "海康"
            ip: 192.168.32.184
            port: 8000
            uname: "admin"
            passwd: "1qaz!QAZ"
            type: hik
    cron-job-list:
      - "* 0 10 * * ?"
    stream-url-prefix: "http://192.168.32.253:8988?src="
  name: "立臻客流统计项目"
